### ISSUE TITLE
Show other syntax output

### ISSUE THREAD

**Issue by Kepete** [robintw/FlaskTemperature#1]
First thank you for you work! I couldn't find any other that worked. 
Your works nicely but I'm having some problems formatting the output. Your code gives out only the temperature, but I need this: 
```
{
    "temperature": 25.8
}
```
the important thing is to point out that I need double quotes, often it changes them to single ones afterwards. Could you help me?

**Comment by robintw** [comment]
Hi - glad you found this useful.

You should be able to replace the line of code here https://github.com/robintw/FlaskTemperature/blob/master/app.py#L10 with the following to get the output you want:

```
temp = get_temperature()
result = '{\n\t"temperature": %s\n}'
return result % (temp)
```

I haven't tested that, but it should include the double-quotes (I wrapped the string in single quotes, so that double quotes still worked inside the string)

**Comment by Kepete** [comment]
Worked perfectly! Thanks!
